# Install tpm:
# git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && tmux source-file ~/.config/tmux/tmux.conf


set-option -sa terminal-overrides ",xterm*:Tc"

set -g mouse on
set -g default-terminal "${TERM}"

# Undercurl support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  

# Needed for image.nvim plugin
set -gq allow-passthrough on
set -g visual-activity off

unbind C-b # unbind prefix key

# New prefix key 
set -g prefix M-space
bind M-space send-prefix

bind M-v copy-mode
bind M-p switch-client -p  
bind M-n switch-client -n  
bind M-l switch-client -l

# open panes in current dir
bind '"' split-window -h -c "#{pane_current_path}"
bind % split-window -v -c "#{pane_current_path}"

set -g base-index 0
set -g pane-base-index 0
set-window-option -g pane-base-index 0
set-option -g renumber-windows on

# Unbind prev/next window
unbind n 
unbind p
bind -n M-H  previous-window
bind -n M-L next-window

unbind x
bind x kill-pane

# bind h select-pane -L
# bind j select-pane -D 
# bind k select-pane -U
# bind l select-pane -R

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n M-S-Up resize-pane -U 5
bind -n M-S-Down resize-pane -D 5
bind -n M-S-Left resize-pane -L 5
bind -n M-S-Right resize-pane -R 5

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.config/tmux/plugins/tpm/tpm'

# theme
source-file ~/.config/tmux/theme.conf

# Set vi-mode
set-window-option -g mode-keys vi

# Modify copy-mode-vi bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy" # system clipboard
bind-key -T copy-mode-vi Y send-keys -X begin-selection \;\
                         send-keys -X end-of-line \;\
                         send-keys -X copy-pipe-and-cancel "wl-copy"
bind-key -T copy-mode-vi :                send-keys -X jump-reverse
bind-key -T copy-mode-vi ,                send-keys -X jump-again
bind-key -T copy-mode-vi \;  command-prompt -p "(goto line)" { send-keys -X goto-line "%%" }

# Scripts
bind M-j new-window 'tmux-sessionizer'
bind M-f new-window 'tms switch'
bind M-0 new-window 'dev-tmux-windowizer'
# bind M-g display-popup -E "tms" 
# bind M-f display-popup -E "tmux-sessionizer" 
# bind M-d display-popup -E "tms switch"
bind M-k run-shell 'tms kill >/dev/null 2>&1'  
bind M-e run-shell 'tmux kill-server >/dev/null 2>&1'

# bind C-r "run-shell 'tms refresh'" 
# bind C-n command-prompt -p "rename active session to: " "run-shell 'tms rename %1'"
# bind C-w command-prompt -p "name of window: " "run-shell 'tmux-windowizer %1'"

# Reduce escape sequences delay
set -g escape-time 10

