---@module 'hl'

-- Sourcing colors generated by wallust
local wallust = require("wallust.wallust-hyprland")

hl.config({
	animations = {
		enabled = false,
	},

	general = {
		gaps_in = 3,
		gaps_out = 9,
		border_size = 2,
		-- gaps_in = 0
		-- gaps_out = 0
		-- col.active_border = $color12
		-- col.inactive_border = $color10
		col = {
			active_border = wallust.color12,
			inactive_border = wallust.background,
		},
	},

	decoration = {
		rounding = 8,
		-- rounding = 0
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		fullscreen_opacity = 1.0,
		dim_inactive = false,
		-- dim_strength = 0.1
		-- dim_special = 0.8
		shadow = {
			enabled = false,
			range = 3,
			render_power = 1,
			-- color =  $color12
			-- color_inactive = $color10
			color = wallust.color2,
			color_inactive = "0x50000000",
		},
		blur = {
			enabled = true,
			-- Less blur
			size = 2,
			passes = 1,
			-- Normal blur
			-- size = 6
			-- passes = 3
			ignore_opacity = true,
			new_optimizations = true,
			special = true,
			popups = true,
		},
	},

	group = {
		groupbar = {
			col = {
				active = wallust.color0,
			},
		},
		col = {
			border_active = wallust.color15,
		},
	},
})

return {}
