-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Vendor defaults for window rules and layerrules

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- =============================================================================
-- DUAL WORKSPACE RULES (match:tag/class -> workspace)
-- =============================================================================

hl.window_rule({
	name = "tag_projects_to_workspace_11",
	match = { tag = "projects*" },
	workspace = "11",
})

hl.window_rule({
	name = "tag_browser_to_workspace_12",
	match = { tag = "browser*" },
	workspace = "12",
})

hl.window_rule({
	name = "tag_file_manager_to_workspace_13",
	match = { tag = "file-manager*" },
	workspace = "13",
})

hl.window_rule({
	name = "class_postman_to_workspace_14",
	match = { class = "^(Postman)$" },
	workspace = "14",
})

hl.window_rule({
	name = "class_spotify_to_workspace_20_silent",
	match = { class = "^(Spotify)$" },
	workspace = "20 silent",
})

-- =============================================================================
-- SINGLE WORKSPACE RULES (match:tag/class -> workspace)
-- =============================================================================

-- hl.window_rule({
-- 	name = "tag_projects_to_workspace_1",
-- 	match = { tag = "projects*" },
-- 	workspace = "1",
-- })
--
-- hl.window_rule({
-- 	name = "tag_browser_to_workspace_2",
-- 	match = { tag = "browser*" },
-- 	workspace = "2",
-- })
--
-- hl.window_rule({
-- 	name = "tag_file_manager_to_workspace_3",
-- 	match = { tag = "file-manager*" },
-- 	workspace = "3",
-- })
--
-- hl.window_rule({
-- 	name = "class_postman_to_workspace_4",
-- 	match = { class = "^(Postman)$" },
-- 	workspace = "4",
-- })
--
-- hl.window_rule({
-- 	name = "class_spotify_to_workspace_0_silent",
-- 	match = { class = "^(Spotify)$" },
-- 	workspace = "0 silent",
-- })

-- =============================================================================
-- TAG ASSIGNMENTS (match:class -> tag +name)
-- =============================================================================

-- Browser tags
hl.window_rule({
	name = "tag_firefox",
	match = { class = "^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr|[Ff]irefox-bin)$" },
	tag = "+browser",
})

hl.window_rule({
	name = "tag_google_chrome",
	match = { class = "^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$" },
	tag = "+browser",
})

hl.window_rule({
	name = "tag_chrome_default",
	match = { class = "^(chrome-.+-Default)$" },
	tag = "+browser",
})

hl.window_rule({
	name = "tag_chromium",
	match = { class = "^([Cc]hromium)$" },
	tag = "+browser",
})

hl.window_rule({
	name = "tag_microsoft_edge",
	match = { class = "^([Mm]icrosoft-edge(-stable|-beta|-dev|-unstable))$" },
	tag = "+browser",
})

hl.window_rule({
	name = "tag_brave",
	match = { class = "^(Brave-browser(-beta|-dev|-unstable)?)$" },
	tag = "+browser",
})

hl.window_rule({
	name = "tag_thorium",
	match = { class = "^([Tt]horium-browser|[Cc]achy-browser)$" },
	tag = "+browser",
})

hl.window_rule({
	name = "tag_zen",
	match = { class = "^(zen)$" },
	tag = "+browser",
})

-- Notif tags
hl.window_rule({
	name = "tag_swaync",
	match = { class = "^(swaync-control-center|swaync-notification-window|swaync-client|class)$" },
	tag = "+notif",
})

-- KooL Settings tags
hl.window_rule({
	name = "tag_kool_cheat",
	match = { title = "^(KooL Quick Cheat Sheet)$" },
	tag = "+KooL_Cheat",
})

hl.window_rule({
	name = "tag_kool_settings",
	match = { title = "^(KooL Hyprland Settings)$" },
	tag = "+KooL_Settings",
})

hl.window_rule({
	name = "tag_nwg",
	match = { class = "^(nwg-displays|nwg-look)$" },
	tag = "+KooL-Settings",
})

-- Terminal tags
hl.window_rule({
	name = "tag_terminal",
	match = { class = "^(Alacritty|foot|kitty|kitty-dropterm)$" },
	tag = "+terminal",
})

-- Email tags
hl.window_rule({
	name = "tag_thunderbird",
	match = { class = "^([Tt]hunderbird|org.gnome.Evolution)$" },
	tag = "+email",
})

hl.window_rule({
	name = "tag_betterbird",
	match = { class = "^(eu.betterbird.Betterbird)$" },
	tag = "+email",
})

hl.window_rule({
	name = "tag_gnome_evolution",
	match = { class = "^(org.gnome.Evolution)$" },
	tag = "+email",
})

-- Project tags
hl.window_rule({
	name = "tag_codium",
	match = { class = "^(codium|codium-url-handler|VSCodium)$" },
	tag = "+projects",
})

hl.window_rule({
	name = "tag_vscode",
	match = { class = "^(VSCode|code|code-url-handler)$" },
	tag = "+projects",
})

hl.window_rule({
	name = "tag_zed",
	match = { class = "^(dev.zed.Zed|antigravity)$" },
	tag = "+projects",
})

-- Screenshare tags
hl.window_rule({
	name = "tag_obs",
	match = { class = "^(com.obsproject.Studio)$" },
	tag = "+screenshare",
})

-- IM tags
hl.window_rule({
	name = "tag_discord",
	match = { class = "^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$" },
	tag = "+im",
})

hl.window_rule({
	name = "tag_ferdium",
	match = { class = "^([Ff]erdium)$" },
	tag = "+im",
})

hl.window_rule({
	name = "tag_whatsapp",
	match = { class = "^([Ww]hatsapp-for-linux)$" },
	tag = "+im",
})

hl.window_rule({
	name = "tag_telegram",
	match = { class = "^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$" },
	tag = "+im",
})

hl.window_rule({
	name = "tag_teams",
	match = { class = "^(teams-for-linux)$" },
	tag = "+im",
})

hl.window_rule({
	name = "tag_element",
	match = { class = "^(im.riot.Riot|Element)$" },
	tag = "+im",
})

-- Game tags
hl.window_rule({
	name = "tag_gamescope",
	match = { class = "^(gamescope)$" },
	tag = "+games",
})

hl.window_rule({
	name = "tag_steam_app",
	match = { class = "^(steam_app_\\d+)$" },
	tag = "+games",
})

-- Gamestore tags
hl.window_rule({
	name = "tag_steam",
	match = { class = "^([Ss]team)$" },
	tag = "+gamestore",
})

hl.window_rule({
	name = "tag_lutris",
	match = { title = "^([Ll]utris)$" },
	tag = "+gamestore",
})

hl.window_rule({
	name = "tag_heroic",
	match = { class = "^(com.heroicgameslauncher.hgl)$" },
	tag = "+gamestore",
})

-- File-manager tags
hl.window_rule({
	name = "tag_thunar",
	match = { class = "^([Tt]hunar|org.gnome.Nautilus|[Pp]cmanfm-qt)$" },
	tag = "+file-manager",
})

hl.window_rule({
	name = "tag_warp",
	match = { class = "^(app.drey.Warp)$" },
	tag = "+file-manager",
})

-- Wallpaper tags
hl.window_rule({
	name = "tag_waytrogen",
	match = { class = "^([Ww]aytrogen)$" },
	tag = "+wallpaper",
})

-- Multimedia tags
hl.window_rule({
	name = "tag_audacious",
	match = { class = "^([Aa]udacious)$" },
	tag = "+multimedia",
})

-- Multimedia-video tags
hl.window_rule({
	name = "tag_mpv_vlc",
	match = { class = "^([Mm]pv|vlc)$" },
	tag = "+multimedia_video",
})

-- Settings tags
hl.window_rule({
	name = "tag_rog_control",
	match = { title = "^(ROG Control)$" },
	tag = "+settings",
})

hl.window_rule({
	name = "tag_wihotspot",
	match = { class = "^(wihotspot(-gui)?)$" },
	tag = "+settings",
})

hl.window_rule({
	name = "tag_baobab",
	match = { class = "^([Bb]aobab|org.gnome.[Bb]aobab)$" },
	tag = "+settings",
})

hl.window_rule({
	name = "tag_gnome_disks",
	match = { class = "^(gnome-disks|wihotspot(-gui)?)$" },
	tag = "+settings",
})

hl.window_rule({
	name = "tag_kvantum",
	match = { title = "(Kvantum Manager)" },
	tag = "+settings",
})

hl.window_rule({
	name = "tag_file_roller",
	match = { class = "^(file-roller|org.gnome.FileRoller)$" },
	tag = "+settings",
})

hl.window_rule({
	name = "tag_nm_applet",
	match = { class = "^(nm-applet|nm-connection-editor|blueman-manager)$" },
	tag = "+settings",
})

hl.window_rule({
	name = "tag_pavucontrol",
	match = { class = "^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$" },
	tag = "+settings",
})

hl.window_rule({
	name = "tag_qt5ct",
	match = { class = "^(qt5ct|qt6ct)$" },
	tag = "+settings",
})

hl.window_rule({
	name = "tag_xdg_desktop_portal",
	match = { class = "(xdg-desktop-portal-gtk)" },
	tag = "+settings",
})

hl.window_rule({
	name = "tag_polkit",
	match = { class = "^(org.kde.polkit-kde-authentication-agent-1)$" },
	tag = "+settings",
})

hl.window_rule({
	name = "tag_rofi",
	match = { class = "^([Rr]ofi)$" },
	tag = "+settings",
})

hl.window_rule({
	name = "tag_btrfs_assistant",
	match = { class = "^(btrfs-assistant)$" },
	tag = "+settings",
})

hl.window_rule({
	name = "tag_timeshift",
	match = { class = "^(timeshift-gtk)$" },
	tag = "+settings",
})

-- Viewer tags
hl.window_rule({
	name = "tag_system_monitor",
	match = { class = "^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter)$" },
	tag = "+viewer",
})

hl.window_rule({
	name = "tag_evince",
	match = { class = "^(evince)$" },
	tag = "+viewer",
})

hl.window_rule({
	name = "tag_eog",
	match = { class = "^(eog|org.gnome.Loupe)$" },
	tag = "+viewer",
})

-- =============================================================================
-- SPECIAL OVERRIDE RULES
-- =============================================================================

-- No blur for multimedia_video
hl.window_rule({
	name = "no_blur_multimedia_video",
	match = { tag = "multimedia_video" },
	no_blur = true,
})

-- Opacity override for multimedia_video
hl.window_rule({
	name = "opacity_multimedia_video",
	match = { tag = "multimedia_video" },
	opacity = "1.0 1.0",
})

-- =============================================================================
-- CENTER POSITION RULES
-- =============================================================================

hl.window_rule({
	name = "center_kool_cheat",
	match = { tag = "KooL_Cheat" },
	center = true,
})

hl.window_rule({
	name = "center_thunar",
	match = { class = "([Tt]hunar)", title = "negative:(.*[Tt]hunar.*)" },
	center = true,
})

hl.window_rule({
	name = "center_rog_control",
	match = { title = "^(ROG Control)$" },
	center = true,
})

hl.window_rule({
	name = "center_kool_settings",
	match = { tag = "KooL-Settings" },
	center = true,
})

hl.window_rule({
	name = "center_keybindings",
	match = { title = "^(Keybindings)$" },
	center = true,
})

hl.window_rule({
	name = "center_pavucontrol",
	match = { class = "^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$" },
	center = true,
})

hl.window_rule({
	name = "center_whatsapp",
	match = { class = "^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$" },
	center = true,
})

hl.window_rule({
	name = "center_ferdium",
	match = { class = "^([Ff]erdium)$" },
	center = true,
})

hl.window_rule({
	name = "move_pip",
	match = { title = "^(Picture-in-Picture)$" },
	move = { "72%", "7%" },
})

-- =============================================================================
-- IDLE INHIBIT FOR FULLSCREEN
-- =============================================================================

hl.window_rule({
	name = "idle_inhibit_fullscreen",
	match = { fullscreen = true },
	idle_inhibit = "fullscreen",
})

-- =============================================================================
-- FLOAT RULES
-- =============================================================================

hl.window_rule({
	name = "float_kool_cheat",
	match = { tag = "KooL_Cheat" },
	float = true,
})

hl.window_rule({
	name = "float_wallpaper",
	match = { tag = "wallpaper" },
	float = true,
})

hl.window_rule({
	name = "float_settings",
	match = { tag = "settings" },
	float = true,
})

hl.window_rule({
	name = "float_viewer",
	match = { tag = "viewer" },
	float = true,
})

hl.window_rule({
	name = "float_kool_settings",
	match = { tag = "KooL-Settings" },
	float = true,
})

hl.window_rule({
	name = "float_zoom",
	match = { class = "([Zz]oom|onedriver|onedriver-launcher)" },
	float = true,
})

hl.window_rule({
	name = "float_calculator",
	match = { class = "(org.gnome.Calculator)", title = "(Calculator)" },
	float = true,
})

hl.window_rule({
	name = "float_mpv",
	match = { class = "^(mpv|com.github.rafostar.Clapper)$" },
	float = true,
})

hl.window_rule({
	name = "float_qalculate",
	match = { class = "^([Qq]alculate-gtk)$" },
	float = true,
})

hl.window_rule({
	name = "float_ferdium",
	match = { class = "^([Ff]erdium)$" },
	float = true,
})

hl.window_rule({
	name = "float_pip",
	match = { title = "^(Picture-in-Picture)$" },
	float = true,
})

-- Float popups and dialogues
hl.window_rule({
	name = "float_authentication",
	match = { title = "^(Authentication Required)$" },
	float = true,
})

hl.window_rule({
	name = "float_codium_popup",
	match = { class = "(codium|codium-url-handler|VSCodium)", title = "negative:(.*codium.*|.*VSCodium.*)" },
	float = true,
})

hl.window_rule({
	name = "float_heroic_popup",
	match = { class = "^(com.heroicgameslauncher.hgl)$", title = "negative:(Heroic Games Launcher)" },
	float = true,
})

hl.window_rule({
	name = "float_steam_popup",
	match = { class = "^([Ss]team)$", title = "negative:^([Ss]team)$" },
	float = true,
})

hl.window_rule({
	name = "float_thunar_popup",
	match = { class = "([Tt]hunar)", title = "negative:(.*[Tt]hunar.*)" },
	float = true,
})

hl.window_rule({
	name = "float_add_folder",
	match = { title = "^(Add Folder to Workspace)$" },
	float = true,
})

hl.window_rule({
	name = "float_save_as",
	match = { title = "^(Save As)$" },
	float = true,
})

hl.window_rule({
	name = "float_open_files",
	match = { initial_title = "(Open Files)" },
	float = true,
})

hl.window_rule({
	name = "float_sddm_background",
	match = { title = "^(SDDM Background)$" },
	float = true,
})

hl.window_rule({
	name = "float_yad",
	match = { class = "^(yad)$", title = "^(YAD)$" },
	float = true,
})

-- =============================================================================
-- OPACITY RULES
-- =============================================================================

hl.window_rule({
	name = "opacity_browser",
	match = { tag = "browser" },
	opacity = "1.0 1.0",
})

hl.window_rule({
	name = "opacity_projects",
	match = { tag = "projects" },
	opacity = "0.9 0.8",
})

hl.window_rule({
	name = "opacity_im",
	match = { tag = "im" },
	opacity = "0.94 0.86",
})

hl.window_rule({
	name = "opacity_multimedia",
	match = { tag = "multimedia" },
	opacity = "0.94 0.86",
})

hl.window_rule({
	name = "opacity_file_manager",
	match = { tag = "file-manager" },
	opacity = "1.0 1.0",
})

hl.window_rule({
	name = "opacity_terminal",
	match = { tag = "terminal" },
	opacity = "0.9 0.9",
})

hl.window_rule({
	name = "opacity_settings",
	match = { tag = "settings" },
	opacity = "0.8 0.7",
})

hl.window_rule({
	name = "opacity_viewer",
	match = { tag = "viewer" },
	opacity = "0.82 0.75",
})

hl.window_rule({
	name = "opacity_wallpaper",
	match = { tag = "wallpaper" },
	opacity = "0.9 0.7",
})

hl.window_rule({
	name = "opacity_text_editor",
	match = { class = "^(gedit|org.gnome.TextEditor|mousepad)$" },
	opacity = "0.8 0.7",
})

hl.window_rule({
	name = "opacity_deluge",
	match = { class = "^(deluge)$" },
	opacity = "0.9 0.8",
})

hl.window_rule({
	name = "opacity_seahorse",
	match = { class = "^(seahorse)$" },
	opacity = "0.9 0.8",
})

-- =============================================================================
-- SIZE RULES
-- =============================================================================

hl.window_rule({
	name = "size_kool_cheat",
	match = { tag = "KooL_Cheat" },
	size = { "(monitor_w*0.65)", "(monitor_h*0.9)" },
})

hl.window_rule({
	name = "size_wallpaper",
	match = { tag = "wallpaper" },
	size = { "(monitor_w*0.7)", "(monitor_h*0.7)" },
})

hl.window_rule({
	name = "size_settings",
	match = { tag = "settings" },
	size = { "(monitor_w*0.7)", "(monitor_h*0.7)" },
})

hl.window_rule({
	name = "size_ferdium",
	match = { class = "^([Ff]erdium)$" },
	size = { "(monitor_w*0.6)", "(monitor_h*0.7)" },
})

hl.window_rule({
	name = "center_calculator",
	match = { class = "(org.gnome.Calculator|qalculate-gtk)" },
	center = true,
})

-- =============================================================================
-- BLUR & FULLSCREEN RULES
-- =============================================================================

hl.window_rule({
	name = "no_blur_games",
	match = { tag = "games" },
	no_blur = true,
})

hl.window_rule({
	name = "fullscreen_games",
	match = { tag = "games" },
	fullscreen = 0,
})

-- =============================================================================
-- NO INITIAL FOCUS RULES
-- =============================================================================

hl.window_rule({
	name = "no_initial_focus_jetbrains",
	match = { class = "^(jetbrains-*)" },
	no_initial_focus = true,
})

hl.window_rule({
	name = "no_initial_focus_wind",
	match = { title = "^(wind.*)$" },
	no_initial_focus = true,
})

-- =============================================================================
-- LAYER RULES
-- =============================================================================

hl.layer_rule({
	match = { namespace = "rofi" },
	blur = true,
})

hl.layer_rule({
	match = { namespace = "notifications" },
	blur = true,
})

hl.layer_rule({
	match = { namespace = "quickshell:overview" },
	blur = true,
})

hl.layer_rule({
	match = { namespace = "quickshell:overview" },
	ignore_alpha = 0.5,
})

-- =============================================================================
-- NAMED RULES FOR SPECIAL CASES
-- =============================================================================

hl.window_rule({
	name = "Whatsapp-zapzap",
	match = { class = "^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$" },
	size = { "(monitor_w*0.6)", "(monitor_h*0.7)" },
	center = true,
})

hl.window_rule({
	name = "Picture-in-Picture",
	match = { title = "^(Picture-in-Picture)$" },
	float = true,
	move = { "72%", "7%" },
	opacity = "0.95 0.75",
	pin = true,
	keep_aspect_ratio = true,
	size = { "(monitor_w*0.3)", "(monitor_h*0.3)" },
})

hl.window_rule({
	name = "Thunar-Progress-bar",
	match = { class = "^(thunar)$", title = "^(File Operation Progress)$" },
	float = true,
	center = true,
	size = { "(monitor_w*0.26)", "(monitor_h*0.18)" },
})

return {}
